---
title: "Publications"
toc: false
---

::: {.callout-tip}
Please visit my [google scholar](https://scholar.google.com/citations?user=xB64MDUAAAAJ) for a full list of publications.
:::

1. **Ru J**, Li P, Wang J, Zhou W, Li B, Huang C, Li P, Guo Z, Tao W, Yang Y, Xu X. TCMSP: a database of systems pharmacology for drug discovery from herbal medicines. Journal of cheminformatics. 2014 Dec;6:1-6.

2. **Ru J**, Khan Mirzaei M, Xue J, Peng X, Deng L. ViroProfiler: a containerized bioinformatics pipeline for viral metagenomic data analysis. Gut Microbes. 2023 Dec 31;15(1):2192522.

3. **Ru J**#, Xue J#, Sun J, Cova L, Deng L. Unveiling the hidden role of aquatic viruses in hydrocarbon pollution bioremediation. Journal of Hazardous Materials. 2023 Aug 15:132299.

4. Ma T#, **Ru J**#, Xue J, Schulz S, Mirzaei MK, Janssen KP, Quante M, Deng L. Differences in gut virome related to barrett esophagus and esophageal adenocarcinoma. Microorganisms. 2021 Aug 10;9(8):1701. 

5. Sun J#, **Ru J**#, Ramos-Mucci L, Qi F, Chen Z, Chen S, Cribbs AP, Deng L, Wang X. DeepsmirUD: Prediction of Regulatory Effects on microRNA Expression Mediated by Small Molecules Using Deep Learning. International Journal of Molecular Sciences. 2023 Jan 18;24(3):1878.

    (#: Co-first author)
